import OrdersTable from "components/Tables/OrdersTable";
import { db } from "firebase.config";
import { collection, DocumentData, getDocs } from "firebase/firestore";
import { GetServerSideProps } from "next";
import Head from "next/head";

import styled from "styled-components";

interface Props {
  users: string;
}

const usersColumn = [
  {
    Header: "User ID",
    accessor: "id" as const, // accessor is the "key" in the data
  },
  {
    Header: "Name",
    accessor: "firstname" as const, // accessor is the "key" in the data
  },
  {
    Header: "E-mail",
    accessor: "email" as const,
  },
  {
    Header: "Phone Number",
    accessor: "phoneNumber" as const,
  },
  {
    Header: "City",
    accessor: "city" as const,
  },
];

export default function Home({ users }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <OrdersTable
        tableData={JSON.parse(users)}
        tableColumns={usersColumn}
        tableName="All Customers"
        path="customers"
      />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const usersRef = collection(db, "users");

  const usersSnap = await getDocs(usersRef);

  const users: DocumentData[] = [];

  usersSnap.forEach((doc) => {
    users.push({
      id: doc.id,
      ...doc.data(),
    });
  });

  return {
    props: {
      users: JSON.stringify(users),
    },
  };
};
